apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  generateName: crossplane-bucket-
  namespace: customer
spec:
  forProvider:
    region: us-east-2
  providerConfigRef:
    name: default
